In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
mc_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/GitHub/AI-ExpertFW-Prj/dataset/modcloth.xlsx')
mc_df.head()

,item_id,waist,size,quality,cup size,hips,bra size,category,bust,height,user_name,length,fit,user_id,shoe size,shoe width,review_summary,review_text
0,123373,29.0,7,5.0,d,38.0,34.0,new,36,5ft 6in,Emily,just right,small,991571,NaN,NaN,NaN,NaN
1,123373,31.0,13,3.0,b,30.0,36.0,new,NaN,5ft 2in,sydneybraden2001,just right,small,587883,NaN,NaN,NaN,NaN
2,123373,30.0,7,2.0,b,NaN,32.0,new,NaN,5ft 7in,Ugggh,slightly long,small,395665,9.0,NaN,NaN,NaN
3,123373,NaN,21,5.0,dd/e,NaN,NaN,new,NaN,NaN,alexmeyer626,just right,fit,875643,NaN,NaN,NaN,NaN
4,123373,NaN,18,5.0,b,NaN,36.0,new,NaN,5ft 2in,dberrones1,slightly long,small,944840,NaN,NaN,NaN,NaN

In [3]:
rr_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/GitHub/AI-ExpertFW-Prj/dataset/renttherunway.xlsx')
rr_df.head()

,fit,user_id,bust size,item_id,weight,rating,rented for,review_text,body type,review_summary,category,height,size,age,review_date
0,fit,420272,34d,2260466,137lbs,10.0,vacation,An adorable romper! Belt and zipper were a lit...,hourglass,So many compliments!,romper,"5' 8""",14,28.0,"April 20, 2016"
1,fit,273551,34b,153475,132lbs,10.0,other,I rented this dress for a photo shoot. The the...,straight & narrow,I felt so glamourous!!!,gown,"5' 6""",12,36.0,"June 18, 2013"
2,fit,360448,NaN,1063761,NaN,10.0,party,This hugged in all the right places! It was a ...,NaN,It was a great time to celebrate the (almost) ...,sheath,"5' 4""",4,116.0,"December 14, 2015"
3,fit,909926,34c,126335,135lbs,8.0,formal affair,I rented this for my company's black tie award...,pear,Dress arrived on time and in perfect condition.,dress,"5' 5""",8,34.0,"February 12, 2014"
4,fit,151944,34b,616682,145lbs,10.0,wedding,I have always been petite in my upper body and...,athletic,Was in love with this dress !!!,gown,"5' 9""",12,27.0,"September 26, 2016"

In [4]:
#mc_df.columns

mc_df.columns = ['item_id', 'waist', 'size', 'quality', 'cup_size', 'hips', 'bra_size',
       'category', 'bust', 'height', 'user_name', 'length', 'fit', 'user_id',
       'shoe_size', 'shoe_width', 'review_summary', 'review_text']

In [6]:
#rr_df.columns

rr_df.columns = ['fit', 'user_id', 'bust_size', 'item_id', 'weight', 'rating',
       'rented_for', 'review_text', 'body_type', 'review_summary', 'category',
       'height', 'size', 'age', 'review_date']

In [7]:
#modcloth_final_data 데이터와 renttherunway데이터 통합을 위한 복사본 생성

mc_df.loc[37313, 'bust'] = 38
mc_df['bust'] = mc_df['bust'].astype('float')

mc_df_cp = mc_df.copy()
rr_df_cp = rr_df.copy()

In [8]:
#modcloth_final_data 데이터 전처리

mc_df_cp.rename(columns={'quality':'rating', 'bra_size':'bust_size'}, inplace = True)

mc_df_cp.drop(['shoe_size', 'shoe_width'], axis = 1, inplace = True)

mc_df_cp.drop(['bust'], axis = 1, inplace = True)

mc_df_cp.drop(mc_df_cp[np.isnan(mc_df_cp['rating'])].index, inplace = True)

mc_df_cp.drop(mc_df_cp[mc_df_cp['height'].isnull()].index, inplace = True)

mc_df_cp.drop(mc_df_cp[(mc_df_cp['review_summary'].isnull()) | (mc_df_cp['review_text'].isnull())].index, inplace = True)

mc_df_cp.drop_duplicates(inplace = True)
#75993 rows × 16 columns -> 75632 rows × 16 columns

mc_df_cp.drop(['waist', 'hips', 'user_name'], axis = 1, inplace = True)

mc_df_cp['rating'] = mc_df_cp['rating']*2

In [9]:
#renttherunway 데이터 전처리

rr_df_cp.drop(rr_df_cp[rr_df_cp['bust_size'].isnull()].index, inplace = True)

rr_df_cp['cup_size'] = rr_df_cp['bust_size'].str[2:]
rr_df_cp['bust_size'] = rr_df_cp['bust_size'].str[:2]
rr_df_cp['bust_size'] = rr_df_cp['bust_size'].astype('float')

rr_df_cp.drop(rr_df_cp[(rr_df_cp['review_summary'].isnull()) | (rr_df_cp['review_text'].isnull())].index, inplace = True)

rr_df_cp.drop(rr_df_cp[np.isnan(rr_df_cp['rating'])].index, inplace = True)

rr_df_cp.drop(rr_df_cp[rr_df_cp['height'].isnull()].index, inplace = True)

rr_df_cp.drop_duplicates(inplace = True)
#173764 rows × 16 columns -> 173594 rows × 16 columns

rr_df_cp.drop(['weight', 'rented_for', 'body_type', 'age', 'review_date'], axis = 1, inplace = True)

In [10]:
# modcloth_final_data 데이터의 bust_size 가 대다수 누락되어 있으므로
# bust_size 데이터가 누락된 user_id 리스트 중 'fit' == 'fit'이고 'length' == 'just right'인 구매건에 대해 
# 동일한 item_id(item 여러개 구매시 여러개 값 가능), size 들의  'fit' == 'fit'이고 'length' == 'just right'인 다른 구매건에 해당하는 고객의 bust_size 사이즈들의 평균을 구해서 
# bust_size 데이터가 누락된 user_id 리스트 각각에 대입

g_by_userid = mc_df_cp[mc_df_cp['bust_size'].isnull() == True].groupby('user_id', axis = 0).count()

user_missing_cnt = pd.DataFrame({'item_cnt': g_by_userid['item_id']}) 

user_missing_cnt.sort_values(by=['item_cnt'], ascending = False, inplace = True)

user_missing_cnt = user_missing_cnt.rename_axis('user_id').reset_index()

#user_missing_cnt_10 = user_missing_cnt.head(10)


hip_mean = 0.0
new_df = pd.DataFrame(columns = {'user_id', 'item_id', 'bust_mean'})
new_df.drop(new_df.index, axis = 0, inplace = True)

#user_missing_cnt_10로 할 경우 상위 10개 고객에 대한 건만 진행, user_missing_cnt의 경우 누락된 값 가진 모든 user_id에 대해 진행(전체로 했을 시 좀 오래걸림)
for index, row in user_missing_cnt.iterrows():
  item_list = mc_df_cp[(mc_df_cp['user_id'] == row[0]) & (mc_df_cp['length'] == 'just right') & (mc_df_cp['fit'] == 'fit')][['user_id', 'item_id', 'size']]
  item_list.reset_index(drop = True, inplace = True)
  leng = len(item_list)
  for i in range(leng) : 
      bust_mean = mc_df_cp[(mc_df_cp['item_id'] == item_list['item_id'][i]) & (mc_df_cp['fit'] == 'fit') & (mc_df_cp['length'] == 'just right') & (mc_df_cp['size'] == item_list['size'][i])]['bust_size'].mean()
      df_temp = pd.DataFrame({'user_id' : [row[0]], 'item_id' : item_list['item_id'][i], 'bust_mean' : bust_mean})
      new_df = new_df.append(df_temp, ignore_index = True)
#12분 48초 소요

new_df_gby = new_df.groupby('user_id', axis = 0).mean()

for index, row in new_df_gby.iterrows():
    if(np.isnan(mc_df_cp.loc[mc_df_cp['user_id'] == index, 'bust_size']).all()):
        mc_df_cp.loc[mc_df_cp['user_id'] == index, 'bust_size'] = row['bust_mean']
    else : 
        mc_df_cp.loc[mc_df_cp['user_id'] == index, 'bust_size'] = max(mc_df_cp.loc[mc_df_cp['user_id'] == index, 'bust_size'])

In [14]:
mc_df_cp.drop(mc_df_cp[mc_df_cp['size'] >= 20].index, inplace = True)

rr_df_cp.drop(rr_df_cp[rr_df_cp['size'] >= 20].index, inplace = True)

,fit,user_id,bust_size,item_id,rating,review_text,review_summary,category,height,size,cup_size
0,fit,420272,34.0,2260466,10.0,An adorable romper! Belt and zipper were a lit...,So many compliments!,romper,"5' 8""",14,d
1,fit,273551,34.0,153475,10.0,I rented this dress for a photo shoot. The the...,I felt so glamourous!!!,gown,"5' 6""",12,b
3,fit,909926,34.0,126335,8.0,I rented this for my company's black tie award...,Dress arrived on time and in perfect condition.,dress,"5' 5""",8,c
4,fit,151944,34.0,616682,10.0,I have always been petite in my upper body and...,Was in love with this dress !!!,gown,"5' 9""",12,b
5,fit,734848,32.0,364092,8.0,Didn't actually wear it. It fit perfectly. The...,Traditional with a touch a sass,dress,"5' 8""",8,b
...,...,...,...,...,...,...,...,...,...,...,...
192539,fit,66386,34.0,2252812,10.0,Fit like a glove!,LOVE IT!!! First Item Im thinking of buying!,jumpsuit,"5' 9""",8,dd
192540,fit,118398,32.0,682043,10.0,The pattern contrast on this dress is really s...,LOVE it!,dress,"5' 1""",4,c
192541,fit,47002,36.0,683251,6.0,"Like the other DVF wraps, the fit on this is f...","Loud patterning, flattering fit",dress,"5' 8""",8,a
192542,fit,961120,36.0,126335,10.0,This dress was PERFECTION. it looked incredib...,loved this dress it was comfortable and photog...,dress,"5' 6""",16,c
192543,fit,123612,36.0,127865,10.0,This dress was wonderful! I had originally pla...,I wore this to a beautiful black tie optional ...,gown,"5' 6""",16,b

In [20]:

mc_df_cp.drop(mc_df_cp[np.isnan(mc_df_cp['bust_size'])].index, inplace = True)

mc_df_cp.drop(['length'], axis = 1, inplace = True)

mc_rr_df = pd.concat([mc_df_cp,rr_df_cp], ignore_index=True)

In [26]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/GitHub/AI-ExpertFW-Prj/dataset')

mc_rr_df.to_excel('modcolth_rentway_integra_data.xlsx', index = False)

mc_df_cp.to_excel('mc_df_cp.xlsx', index = False)

rr_df_cp.to_excel('rr_df_cp.xlsx', index = False)

mc_rr_df_read = pd.read_excel('modcolth_rentway_integra_data.xlsx')